name: Go CICD

on:
  push:
    branches: 
      - master
      - feature/sj
jobs:
  docker-push:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/secretproj:v1
  docker-deploy:
    needs: docker-push
    runs-on: ubuntu-latest 
    steps:
    - name: deploying app in self-hosted runner.
      env:
       PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
       USERNAME: ${{ secrets.DOCKER_USERNAME }}  
      run: |
              docker login -u $USERNAME -p $PASSWORD  
              docker run sugamdocker35/secretproj:v1

